export const queries = [
    "What is the time complexity of quicksort in the worst case?",
    "How does a blockchain ensure security and immutability?",
    "What is the difference between synchronous and asynchronous programming?",
    "Explain the concept of a REST API vs. a GraphQL API.",
    "What are the key differences between React and Vue.js?",
    "How do databases use indexing to speed up queries?",
    "What is the purpose of a load balancer in web applications?",
    "How do neural networks learn from data in machine learning?",
    "What is the difference between a compiled and an interpreted language?",
    "What are the benefits of using Docker for application deployment?",
    "What are the key factors that determine inflation?",
    "How does supply and demand affect market prices?",
    "What is the difference between fiscal policy and monetary policy?",
    "Explain the concept of Gross Domestic Product (GDP).",
    "How do interest rates impact economic growth?",
    "What is the difference between a bear market and a bull market?",
    "How does cryptocurrency mining work?",
    "What are the advantages and risks of investing in stocks?",
    "How do central banks control money supply?",
    "What is the role of venture capital in startups?",
    "What is the theory of relativity and why is it important?",
    "How does CRISPR technology work in gene editing?",
    "What are black holes, and how do they form?",
    "How does nuclear fusion differ from nuclear fission?",
    "What causes climate change, and what are its effects?",
    "How does artificial intelligence impact scientific research?",
    "What is the function of mitochondria in a cell?",
    "Why is quantum computing considered revolutionary?",
    "What are the benefits and risks of genetically modified organisms (GMOs)?",
    "How does a solar panel convert sunlight into electricity?",
    "What factors influence stock market trends?",
    "How do companies determine the price of their products?",
    "What is the significance of branding in marketing?",
    "How does e-commerce affect traditional retail businesses?",
    "What are the key principles of digital marketing?",
    "How do businesses use data analytics to improve sales?",
    "What are the advantages and disadvantages of franchising?",
    "How do advertising algorithms work on social media platforms?",
    "What is the role of a startup incubator in business growth?",
    "How does customer psychology affect purchasing decisions?",
]   